services:
  etl-sink:
    image: postgres
    container_name: etl-sink
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/load-data.sh:/docker-entrypoint-initdb.d/load-data.sh
      - ./db/csv:/csv
    restart: unless-stopped

  etl-pipeline:
    build: ./app
    container_name: etl-pipeline
    depends_on:
      - etl-sink
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["./wait-for-postgres.sh", "python", "main.py"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

volumes:
  pgdata:
