services:
  etl-sink:
    image: postgres
    container_name: etl-sink
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/load-data.sh:/docker-entrypoint-initdb.d/load-data.sh
      - ./db/csv:/csv
    restart: unless-stopped

volumes:
  pgdata:
