services:
  etl-target:
    image: postgres
    container_name: etl-target
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_DB_PORT}:${DB_PORT}"
    volumes:
      - target_pgdata:/var/lib/postgresql/data 
      - ./db/etl-target/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/etl-target/load-data.sh:/docker-entrypoint-initdb.d/load-data.sh
      - ./db/etl-target/csv:/csv
    restart: unless-stopped

  etl-stage:
    image: postgres
    container_name: etl-stage
    environment:
      POSTGRES_USER: ${STAGE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STAGE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STAGE_POSTGRES_DB}
    ports:
      - "${HOST_STAGE_DB_PORT}:${STAGE_DB_PORT}"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - stage_pgdata:/var/lib/postgresql/data 
      - ./db/etl-stage/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  etl-server:
    build: ./etl-server
    container_name: etl-server
    depends_on:
      - etl-target
    volumes:
      - ./etl-server:/etl-server
    working_dir: /etl-server
    command: ["./wait-for-postgres.sh", "python", "main.py"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      STAGE_DB_HOST: ${STAGE_DB_HOST}
      STAGE_DB_NAME: ${STAGE_DB_NAME}
      STAGE_DB_USER: ${STAGE_DB_USER}
      STAGE_DB_PASS: ${STAGE_DB_PASS}
      STAGE_DB_PORT: ${STAGE_DB_PORT}

  sensor-client-1:
    build:  ./sensor-client
    container_name: sensor-client-1
    working_dir: /app
    volumes:
      - ./data:/data:ro
    environment:
      SENSOR_ID: "1"
      SERVER_HOST: etl-server
      SERVER_PORT: 5555 

  sensor-client-2:
    build:  ./sensor-client
    container_name: sensor-client-2
    working_dir: /app
    volumes:
      - ./data:/data:ro
    environment:
      SENSOR_ID: "2"
      DB_PORT: 5432
      SERVER_HOST: etl-server
      SERVER_PORT: 5555 


  sensor-client-3:
    build:  ./sensor-client
    container_name: sensor-client-3
    working_dir: /app
    volumes:
      - ./data:/data:ro
    environment:
      SENSOR_ID: "3"
      DB_PORT: 5432
      SERVER_HOST: etl-server
      SERVER_PORT: 5555 

  sensor-client-4:
    build:  ./sensor-client
    container_name: sensor-client-4
    working_dir: /app
    volumes:
      - ./data:/data:ro
    environment:
      SENSOR_ID: "4"
      DB_PORT: 5432
      SERVER_HOST: etl-server
      SERVER_PORT: 5555 

  sensor-client-5:
    build:  ./sensor-client
    container_name: sensor-client-5
    working_dir: /app
    volumes:
      - ./data:/data:ro
    environment:
      SENSOR_ID: "5"
      DB_PORT: 5432
      SERVER_HOST: etl-server
      SERVER_PORT: 5555 

volumes:
  target_pgdata:
  stage_pgdata:
